apiVersion: gcp.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  projectID: devops-labs-397603 
  credentials:
    impersonateServiceAccount:
      name: my-default@my-project.iam.gserviceaccount.com
    source: ImpersonateServiceAccount