apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pubsub-v1
  title: Create PubSub Topic via Crossplane
  description: Gera um manifesto Crossplane e abre um PR no repositório de GitOps.
  tags:
    - app-infra
spec:
  owner: team-platform
  type: service

  parameters:
    - title: Dados do Topic
      required:
        - topicname
        - environment
      properties:
        topicname:
          title: Topic Name
          type: string
          description: Nome único do tópico PubSub.
        environment:
          title: Environment
          type: string
          enum:
            - integration
            - pre-prod
            - prod
          default: integration
        team:
          title: Team
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group

  steps:
    # 1. Busca a PASTA de templates. 
    # Ele vai processar todos os arquivos lá dentro (incluindo o que renomeamos para {{name}}.yaml)
    - id: fetch-template
      name: Fetch Crossplane Template
      action: fetch:template
      input:
        # Apontamos para a PASTA, não para o arquivo direto.
        # O Backstage assume que o caminho é relativo ao local deste template.
        url: ./skeleton
        values:
          name: ${{ parameters.topicname }}
          environment: ${{ parameters.environment }}
          team: ${{ parameters.team }}
        targetPath: ./infra-temp

    # 2. Abre o Pull Request
    - id: create-pr
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=gitops-app-infra&owner=marcelo-luizz
        branchName: create-topic-${{ parameters.topicname }}
        title: "feat(pubsub): add topic ${{ parameters.topicname }} in ${{ parameters.environment }}"
        description: "Este PR foi gerado via Backstage."
        # Pegamos o arquivo renderizado na pasta temporária
        sourcePath: ./infra-temp
        # E jogamos para a pasta de destino final no GitOps
        targetPath: environments/${{ parameters.environment }}/team-platform/pubsub/${{ parameters.topicname }}

  output:
    links:
      - title: Acompanhar Pull Request
        url: ${{ steps['create-pr'].output.remoteUrl }}
