apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: ${{ values.name }}-sa
  namespace: crossplane-system
spec:
  deletionPolicy: Delete
  forProvider:
    description: perfection
    displayName: a beautiful service account
  providerConfigRef:
    kind: ProviderConfig
    name: default
---
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountPolicy
metadata:
  name: ${{ values.name }}-sa-policy
  namespace: crossplane-system
spec:
  forProvider:
    policy:
      bindings:
        - members:
            - serviceAccount:PROJECT_ID.svc.id.goog[K8S_NAMESPACE/KSA_NAME]
          role: roles/iam.workloadIdentityUser
    serviceAccountRef:
      name: ${{ values.name }}-sa
  providerConfigRef:
    kind: ProviderConfig
    name: default