apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-standard
  labels:
    provider: gcp
    service: storage
    crossplane.io/xrd: xbuckets.jeitto.io
spec:
  compositeTypeRef:
    apiVersion: jeitto.io/v1alpha1
    kind: XBucket
  resources:
    - name: bucket
      base:
        apiVersion: storage.gcp.upbound.io/v1beta2
        kind: Bucket
        spec:
          forProvider:
            location: southamerica-east1
            storageClass: STANDARD
            # ===== SECURITY BY DESIGN — Dev não controla isso =====
            publicAccessPrevention: enforced
            uniformBucketLevelAccess: true
            versioning:
              - enabled: true
            labels:
              managed-by: crossplane
          providerConfigRef:
            name: gcp-integration
      patches:
        # --- Inputs do dev ---
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.location
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.storageClass
          toFieldPath: spec.forProvider.storageClass
        # --- Labels automáticas ---
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.team
          toFieldPath: spec.forProvider.labels.team
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: spec.forProvider.labels.environment
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.forProvider.labels.claim-name
        # --- ProviderConfig por ambiente ---
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: map
              map:
                integration: gcp-integration
                pre-prod: gcp-pre-prod
                prod: gcp-prod
        # --- Status ---
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.bucketName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.url
          toFieldPath: status.bucketUrl
