apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: serviceaccount-standard
  labels:
    provider: gcp
    service: iam
    crossplane.io/xrd: xserviceaccounts.jeitto.io
spec:
  compositeTypeRef:
    apiVersion: jeitto.io/v1alpha1
    kind: XServiceAccount
  resources:
    - name: service-account
      base:
        apiVersion: cloudplatform.gcp.upbound.io/v1beta1
        kind: ServiceAccount
        spec:
          forProvider:
            displayName: ""
            description: "Managed by Crossplane"
          providerConfigRef:
            name: gcp-integration
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.displayName
          toFieldPath: spec.forProvider.displayName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.description
          toFieldPath: spec.forProvider.description
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.environment
          toFieldPath: spec.providerConfigRef.name
          transforms:
            - type: map
              map:
                integration: gcp-integration
                pre-prod: gcp-pre-prod
                prod: gcp-prod
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.email
          toFieldPath: status.email
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.uniqueId
          toFieldPath: status.uniqueId
