apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  annotations:
  labels:
    example: 'true'
  name: ${{ values.name }}
spec:
  deletionPolicy: Delete
  location: US
  providerConfigRef:
    name: default
    kind: ProviderConfig
  storageClass: MULTI_REGIONAL
