apiVersion: sql.gcp.m.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: ${{ values.name }}
  namespace: crossplane-system
spec:
  forProvider:
    databaseVersion: MYSQL_5_7
    deletionProtection: false
    region: us-central1
    settings:
      diskSize: 20
      tier: db-f1-micro
  providerConfigRef:
    name: default
    kind: ProviderConfig
  writeConnectionSecretToRef:
    name: ${{ values.name }}-sql-db-instance-secret