apiVersion: storage.gcp.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ${{ values.name }}
  namespace: crossplane-system
spec:
  forProvider:
    location: US
  providerConfigRef:
    kind: ProviderConfig
    name: default