apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.jeitto.io
spec:
  group: jeitto.io
  names:
    kind: XDatabase
    plural: xdatabases
  claimNames:
    kind: DatabaseClaim
    plural: databaseclaims
  defaultCompositionRef:
    name: database-postgresql
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  required:
                    - environment
                    - team
                    - engine
                  properties:
                    environment:
                      type: string
                      enum:
                        - integration
                        - pre-prod
                        - prod
                    team:
                      type: string
                    engine:
                      type: string
                      description: "Database engine"
                      enum:
                        - POSTGRES_15
                        - POSTGRES_14
                        - MYSQL_8_0
                    tier:
                      type: string
                      description: "CloudSQL machine tier"
                      default: db-custom-2-7680
                      enum:
                        - db-f1-micro
                        - db-g1-small
                        - db-custom-2-7680
                        - db-custom-4-15360
                        - db-custom-8-30720
                    diskSizeGb:
                      type: integer
                      default: 20
                      minimum: 10
                      maximum: 1000
                    highAvailability:
                      type: boolean
                      description: "Enable HA (regional) — recommended for prod"
                      default: false
                    enableBackups:
                      type: boolean
                      default: true
                    region:
                      type: string
                      default: southamerica-east1
            status:
              type: object
              properties:
                connectionName:
                  type: string
                privateIpAddress:
                  type: string
