apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xserviceaccounts.jeitto.io
spec:
  group: jeitto.io
  names:
    kind: XServiceAccount
    plural: xserviceaccounts
  claimNames:
    kind: ServiceAccountClaim
    plural: serviceaccountclaims
  defaultCompositionRef:
    name: serviceaccount-standard
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  required:
                    - environment
                    - team
                    - displayName
                  properties:
                    environment:
                      type: string
                      enum:
                        - integration
                        - pre-prod
                        - prod
                    team:
                      type: string
                    displayName:
                      type: string
                      description: "Human-readable name for the service account"
                    description:
                      type: string
                      description: "Description of the service account purpose"
                      default: "Managed by Crossplane"
            status:
              type: object
              properties:
                email:
                  type: string
                uniqueId:
                  type: string
