apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-gcp-compute
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-compute:v1.14.1
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
