apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pubsub
  title: Create PubSub, Topic e Subscription via Crossplane
  description: Gera um manifesto Crossplane e abre um PR no repositório de GitOps.
  tags:
    - gcp
    - crossplane
    - infrastructure
spec:
  owner: team-platform
  type: service
  parameters:
    - title: Dados do PubSub
      required:
        - scope
        - pubsubName
        - environment
      properties:
        scope:
          title: Escopo de Implantação
          type: string
          ui:widget: radio
          description: |
            * **App Infra (Padrão):** Para recursos que servem diretamente sua aplicação (PubSub, Buckets). Uso geral para times de engenharia.
            * **Core Infra:** Para componentes de base e fundação. Uso restrito ao time de Plataforma/SRE.
          enum:
            - app-infra
            - core-infra
          enumNames:
            - "App Infra (Uso Geral para Times de Engenharia)"
            - "Core Infra (Infraestrutura de Base/Plataforma)"
        pubsubName:
          title: PubSub Name
          type: string
          description: Nome único do PubSub.
        region:
          title: Region
          type: string
          enum:
            - us-central1
            - us-east1
            - southamerica-east1
          default: southamerica-east1  
        environment:
          title: Environment
          type: string
          enum:
            - stage
            - homolog
            - prod
          default: stage
        team:
          title: Time Responsável
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    - id: fetch-template
      name: Fetch Crossplane Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.pubsubName }}
          environment: ${{ parameters.environment }}
          team: ${{ parameters.team }}
          region: ${{ parameters.region }}
          scope: ${{ parameters.scope }}
        targetPath: ./infra-temp

    - id: create-pr
      name: Criando Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: >-
          ${{ 'github.com?repo=gitops-app-infra&owner=marcelo-luizz' if parameters.scope == 'app-infra' 
              else 'github.com?repo=gitops-core-infra&owner=marcelo-luizz' }}
        
        branchName: "infra-${{ parameters.scope }}-${{ parameters.pubsubName }}"
        title: "infra(${{ parameters.scope }}): add ${{ parameters.pubsubName }} em ${{ parameters.environment }}"
        description: |
          ### 🚀 Novo Recurso de Infraestrutura
          - **Tipo:** ${{ parameters.scope }}
          - **Ambiente:** ${{ parameters.environment }}
          - **Time:** ${{ (parameters.team | parseEntityRef).name }}
          
          Gerado automaticamente via Backstage IDP.
        
        sourcePath: ./infra-temp
        
        # CAMINHO CORRIGIDO AQUI:
        targetPath: >-
          ${{ 'environments/' + parameters.environment + '/teams/'  + (parameters.team | parseEntityRef).name + '/southamerica-east1/pubsub/' + parameters.pubsubName if parameters.scope == 'app-infra' 
              else 'environments/' + parameters.environment + '/southamerica-east1/pubsub/' + parameters.pubsubName }}

  output:
    links:
      - title: "🔗 Acompanhar Pull Request no GitHub"
        url: ${{ steps['create-pr'].output.remoteUrl }}
    text:
      - title: "📘 Como funciona este provisionamento?"
        content: |
          Parabéns! O seu recurso foi solicitado.

          ### 🚀 Fluxo de Provisionamento
          ![Fluxo GitOps](https://raw.githubusercontent.com/marcelo-luizz/gitops-core-infra/main/backstage-templates/gcp/compute-engine/gitops-app-infra.png)

          ### 📂 Destino do Manifesto
          O arquivo foi enviado para o repositório **gitops-${{ parameters.scope }}**.
          
          **Caminho final:**
          `environments/${{ parameters.environment }}/${{ (parameters.team | parseEntityRef).name if parameters.scope == 'app-infra' else 'southamerica-east1' }}/pubsub/${{ parameters.pubsubName }}`