# apiVersion: sql.gcp.m.upbound.io/v1beta1
# kind: DatabaseInstance
# metadata:
#   name: ${{ values.name }}
#   namespace: crossplane-system
# spec:
#   forProvider:
#     databaseVersion: MYSQL_5_7
#     deletionProtection: false
#     region: us-central1
#     settings:
#       diskSize: 20
#       tier: db-f1-micro
#   providerConfigRef:
#     name: default
#     kind: ProviderConfig
#   writeConnectionSecretToRef:
#     name: ${{ values.name }}-sql-db-instance-secret

---
# Tópico Principal
apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: Topic
metadata:
  name: ${{ values.name }}-topic
  labels:
    team: ${{ (values.team | parseEntityRef).name if values.team else "no-team" }}
    env: ${{ values.environment }}
    resource-name: ${{ values.name }}
spec:
  forProvider: {}
  providerConfigRef:
    name: default

---
# Subscription Principal
apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: Subscription
metadata:
  name: ${{ values.name }}-subscription
  labels:
    team: ${{ (values.team | parseEntityRef).name if values.team else "no-team" }}
    env: ${{ values.environment }}
    resource-name: ${{ values.name }}-subscription
spec:
  forProvider:
    topicSelector:
      matchLabels:
        resource-name: ${{ values.name }}-topic
    ackDeadlineSeconds: 20
    {% if values.dlqEnabled == true or values.dlqEnabled == "true" %}
    deadLetterPolicy:
      - deadLetterTopicSelector:
          matchLabels:
            resource-name: ${{ values.name }}-dlq
        maxDeliveryAttempts: 5
    {% endif %}
  providerConfigRef:
    name: default

{% if values.dlqEnabled == true or values.dlqEnabled == "true" %}
---
# Tópico de DLQ
apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: Topic
metadata:
  name: ${{ values.name }}-dlq
  labels:
    team: ${{ (values.team | parseEntityRef).name if values.team else "no-team" }}
    env: ${{ values.environment }}
    resource-name: ${{ values.name }}-dlq
spec:
  forProvider: {}
  providerConfigRef:
    name: default

---
# Subscription de DLQ (Para drenar as mensagens presas)
apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: Subscription
metadata:
  name: ${{ values.name }}-dlq
  labels:
    team: ${{ (values.team | parseEntityRef).name if values.team else "no-team" }}
    env: ${{ values.environment }}
    resource-name: ${{ values.name }}-dlq-subscription
spec:
  forProvider:
    topicSelector:
      matchLabels:
        resource-name: ${{ values.name }}-dlq
    ackDeadlineSeconds: 20
  providerConfigRef:
    name: default

---
# Permissão Necessária: PubSub Service Agent -> Publicar na DLQ
apiVersion: pubsub.gcp.m.upbound.io/v1beta1
kind: TopicIAMMember
metadata:
  name: "${{ values.name }}-dlq-auth"
spec:
  forProvider:
    role: roles/pubsub.publisher
    # Service Agent padrão do PubSub (O número 509332012213 é o do seu projeto atual)
    member: "serviceAccount:service-509332012213@gcp-sa-pubsub.iam.gserviceaccount.com"
    topicSelector:
      matchLabels:
        resource-name: ${{ values.name }}-dlq
  providerConfigRef:
    name: default
{% endif %}