apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-infra-environments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/marcelo-luizz/gitops-app-infra
        revision: HEAD
        directories:
          - path: environments/*
  template:
    metadata:
      name: "app-infra-{{.path.basename}}-bootstrap"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/marcelo-luizz/gitops-app-infra
        targetRevision: HEAD
        path: "{{.path.path}}"
        directory:
          recurse: true
          include: "{**/*.yaml,**/*.yml}"
      destination:
        server: https://kubernetes.default.svc
        namespace: crossplane-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
