apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-addons
  source:
    repoURL: "https://github.com/jeitto/gitops-core-infra.git"
    targetRevision: HEAD
    path: argocd/cluster-addons/gateway-manifests/external
  destination:
    namespace: gateway
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
